eureka:
 instance:
  hostname: localhost

resilience4j:
 circuitbreaker:
   instances:
    userService:
     registerHealthIndicator: true
     slidingWindowType: COUNT_BASED
     slidingWindowSize: 10
     minimumNumberOfCalls: 5
     failureRateThreshold: 50
     permittedNumberOfCallsInHalfOpenState: 3
     waitDurationInOpenState: 20s
     automaticTransitionFromOpenToHalfOpenEnabled: true